# PowerShell script for easy setup and running of the Route Optimizer

#Generated by GPT I did not make this needs to be tested

Write-Host "🚚 Truck Route Optimizer - Setup Script" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Green

# Check Python installation
Write-Host "`n1. Checking Python installation..." -ForegroundColor Yellow
try {
    $pythonVersion = python --version 2>&1
    Write-Host "   ✅ $pythonVersion" -ForegroundColor Green
} catch {
    Write-Host "   ❌ Python not found. Please install Python 3.9+ from python.org" -ForegroundColor Red
    exit 1
}

# Check if requirements.txt exists
if (-not (Test-Path "requirements.txt")) {
    Write-Host "   ❌ requirements.txt not found!" -ForegroundColor Red
    exit 1
}

# Install dependencies
Write-Host "`n2. Installing dependencies..." -ForegroundColor Yellow
Write-Host "   This may take a few minutes..." -ForegroundColor Cyan

try {
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    Write-Host "   ✅ Dependencies installed successfully" -ForegroundColor Green
} catch {
    Write-Host "   ⚠️ Some dependencies may have failed to install" -ForegroundColor Yellow
    Write-Host "   You can continue with basic functionality" -ForegroundColor Yellow
}

# Check .env file
Write-Host "`n3. Checking configuration..." -ForegroundColor Yellow
if (-not (Test-Path ".env")) {
    Write-Host "   ⚠️ .env file not found" -ForegroundColor Yellow
    Write-Host "   Creating .env template..." -ForegroundColor Cyan
    
    $envContent = @"
# OpenRouteService API Key (get free key from: https://openrouteservice.org/dev/#/signup)
OPENROUTESERVICE_API_KEY=your_api_key_here

# Optimization Parameters
MAX_VEHICLE_CAPACITY=200
MAX_ROUTE_DURATION_HOURS=8
DEFAULT_SPEED_KMH=40

# Time Settings
START_TIME=09:00
WORKING_HOURS=8
"@
    
    $envContent | Out-File -FilePath ".env" -Encoding UTF8
    Write-Host "   ✅ .env template created" -ForegroundColor Green
    Write-Host "   📝 Edit .env file to add your OpenRouteService API key" -ForegroundColor Cyan
} else {
    Write-Host "   ✅ .env file exists" -ForegroundColor Green
}

# Create output directory
Write-Host "`n4. Setting up directories..." -ForegroundColor Yellow
if (-not (Test-Path "output")) {
    New-Item -ItemType Directory -Path "output" | Out-Null
    Write-Host "   ✅ Output directory created" -ForegroundColor Green
} else {
    Write-Host "   ✅ Output directory exists" -ForegroundColor Green
}

# Run basic test
Write-Host "`n5. Running basic functionality test..." -ForegroundColor Yellow
try {
    python test_system.py
    $testResult = $LASTEXITCODE
    if ($testResult -eq 0) {
        Write-Host "   ✅ Basic tests passed" -ForegroundColor Green
    } else {
        Write-Host "   ⚠️ Some tests failed, but you can still proceed" -ForegroundColor Yellow
    }
} catch {
    Write-Host "   ⚠️ Test script failed to run" -ForegroundColor Yellow
}

# Display usage instructions
Write-Host "`n" + "=" * 50 -ForegroundColor Green
Write-Host "🎉 Setup Complete!" -ForegroundColor Green
Write-Host "`n📋 Available Commands:" -ForegroundColor Cyan

Write-Host "`n   Quick Start (with sample data):" -ForegroundColor White
Write-Host "   python main.py generate-sample" -ForegroundColor Gray
Write-Host "   python main.py optimize" -ForegroundColor Gray

Write-Host "`n   Custom Data:" -ForegroundColor White
Write-Host "   python main.py optimize --trucks your_trucks.json --deliveries your_deliveries.json" -ForegroundColor Gray

Write-Host "`n   Simulate Truck Failure:" -ForegroundColor White
Write-Host "   python main.py simulate-failure --failed-truck 0" -ForegroundColor Gray

Write-Host "`n   Start API Server:" -ForegroundColor White
Write-Host "   python main.py api" -ForegroundColor Gray
Write-Host "   # Then visit: http://localhost:8000/docs" -ForegroundColor Gray

Write-Host "`n   Generate More Sample Data:" -ForegroundColor White
Write-Host "   python main.py generate-sample --trucks 5 --deliveries 20" -ForegroundColor Gray

Write-Host "`n📁 Output Files:" -ForegroundColor Cyan
Write-Host "   • output/routes.json          - Optimized route assignments" -ForegroundColor Gray
Write-Host "   • output/eta_schedule.json    - Estimated arrival times" -ForegroundColor Gray
Write-Host "   • output/route_map.html       - Interactive map visualization" -ForegroundColor Gray
Write-Host "   • output/summary.json         - Optimization statistics" -ForegroundColor Gray

Write-Host "`n🔑 API Key Setup:" -ForegroundColor Cyan
Write-Host "   1. Visit: https://openrouteservice.org/dev/#/signup" -ForegroundColor Gray
Write-Host "   2. Get free API key" -ForegroundColor Gray
Write-Host "   3. Edit .env file and replace 'your_api_key_here' with your key" -ForegroundColor Gray
Write-Host "   4. Restart the application for real-world routing" -ForegroundColor Gray

Write-Host "`n⚡ Quick Test:" -ForegroundColor Cyan
Write-Host "   python main.py generate-sample && python main.py optimize" -ForegroundColor Gray

Write-Host "`n" + "=" * 50 -ForegroundColor Green
